export const GET_COUNTRY = 'GET_COUNTRY';

export const FILTER_POR_CONTINENTE = 'FILTER_POR_CONTINENTE';

export const GET_PAIS_NOMBRE = 'GET_PAIS_NOMBRE';

export const GET_PAIS_ID = 'GET_PAIS_ID';

export const GET_ACTIVIDAD = 'GET_ACTIVIDAD';

export const PUT_ACTIVIDAD = 'PUT_ACTIVIDAD';

export const ADD_ACTIVIDAD = 'ADD_ACTIVIDAD';

export const FILTER_POR_TEMPORADA = 'FILTER_POR_TEMPORADA';

export const DELETE_ACTIVIDAD = 'DELETE_ACTIVIDAD';

export const ORDENAR_POR_NOMBRE = 'ORDENAR_POR_NOMBRE';

export const ORDENAR_POR_POBLACION = 'ORDENAR_POR_POBLACION';
