export const GET_ACTIVIDAD = 'GET_ACTIVIDAD';

export const ADD_ACTIVIDAD = 'ADD_ACTIVIDAD';

export const PUT_ACTIVIDAD = 'PUT_ACTIVIDAD';

export const DELETE_ACTIVIDAD = 'DELETE_ACTIVIDAD';

export const FILTRAR_POR_CONTINENTE = 'FILTRAR_POR_CONTINENTE';

export const FILTRAR_POR_TEMPORADA = 'FILTRAR_POR_TEMPORADA';

export const ORDENAR_POR_NOMBRE = 'ORDENAR_POR_NOMBRE';

export const ORDENAR_POR_POBLACION = 'ORDENAR_POR_POBLACION';

export const GET_PAIS_NOMBRE = 'GET_PAIS_NOMBRE';

export const GET_PAIS_ID = 'GET_PAIS_ID';